name: Generate Static Site

on:
    push:
        branches:
            - trunk
    workflow_dispatch:


jobs:
    # Build job
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: write  # to deploy to Pages
        timeout-minutes: 5
        env:
            REPO: ${{ github.repository }}
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: 'Install bun'
              run: |
                  curl -fsSL https://bun.sh/install | bash
            - name: Generate static site
              run: PATH="${PATH}:${HOME}/.bun/bin" bash build-static-site.sh
            - name: Deploy
              uses: peaceiris/actions-gh-pages@v4
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                publish_dir: ./output
                