name: Generate Static Site

on:
    push:
        branches:
            - trunk


jobs:
    # Build job
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: write      # to deploy to Pages

        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Generate static site
              run: node generate-static-site.js
            - name: Deploy
              uses: peaceiris/actions-gh-pages@v4
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                publish_dir: ./out
                